/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admim;

import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Andriel
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuGerenciarJogador = new javax.swing.JMenuItem();
        mnuListarJogador = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenu();
        mnuGerenciarPergunta = new javax.swing.JMenuItem();
        mnuGerenciarLista = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuListarRanking = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Jogador");

        mnuGerenciarJogador.setText("GerenciarJogador");
        mnuGerenciarJogador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGerenciarJogadorActionPerformed(evt);
            }
        });
        jMenu1.add(mnuGerenciarJogador);

        mnuListarJogador.setText("ListarJogador");
        mnuListarJogador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuListarJogadorActionPerformed(evt);
            }
        });
        jMenu1.add(mnuListarJogador);

        jMenuBar1.add(jMenu1);

        jMenuBar2.setText("Pergunta");

        mnuGerenciarPergunta.setText("Gerenciar");
        mnuGerenciarPergunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGerenciarPerguntaActionPerformed(evt);
            }
        });
        jMenuBar2.add(mnuGerenciarPergunta);

        mnuGerenciarLista.setText("Listar");
        mnuGerenciarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGerenciarListaActionPerformed(evt);
            }
        });
        jMenuBar2.add(mnuGerenciarLista);

        jMenuBar1.add(jMenuBar2);

        jMenu2.setText("Ranking");

        mnuListarRanking.setText("Listar");
        mnuListarRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuListarRankingActionPerformed(evt);
            }
        });
        jMenu2.add(mnuListarRanking);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuGerenciarJogadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGerenciarJogadorActionPerformed
       jogadorManter tela = new jogadorManter();
      //fechar aoenas a janela
      tela.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
      tela.setVisible(true);
    }//GEN-LAST:event_mnuGerenciarJogadorActionPerformed

    private void mnuListarJogadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuListarJogadorActionPerformed
       jogadorListar tela = new jogadorListar();
      //fechar apenas a janela
      tela.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
      tela.setVisible(true);
    }//GEN-LAST:event_mnuListarJogadorActionPerformed

    private void mnuGerenciarPerguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGerenciarPerguntaActionPerformed
      perguntaManter tela = new perguntaManter();
      //fechar apenas a janela
      tela.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
      tela.setVisible(true);
    }//GEN-LAST:event_mnuGerenciarPerguntaActionPerformed

    private void mnuGerenciarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGerenciarListaActionPerformed
       perguntaListar tela = new perguntaListar();
      //fechar apenas a janela
      tela.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
      tela.setVisible(true);
    }//GEN-LAST:event_mnuGerenciarListaActionPerformed

    private void mnuListarRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuListarRankingActionPerformed
        rankingListar tela = null;
        try {
            tela = new rankingListar();
        } catch (ParseException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
        tela.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        tela.setVisible(true);
    }//GEN-LAST:event_mnuListarRankingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuBar2;
    private javax.swing.JMenuItem mnuGerenciarJogador;
    private javax.swing.JMenuItem mnuGerenciarLista;
    private javax.swing.JMenuItem mnuGerenciarPergunta;
    private javax.swing.JMenuItem mnuListarJogador;
    private javax.swing.JMenuItem mnuListarRanking;
    // End of variables declaration//GEN-END:variables
}
